### ISSUE TITLE
What is the full IMessageBus lifecyle?

### ISSUE THREAD

**Issue by unruledboy** [zarusz/SlimMessageBus#14]
So I read all the available documents (all the Readme.md files), and I would like to get clarification on the lifecyle of the IMessageBus.

Let's take the Domain Events sample as an example. In a typical web application, incoming request made -> create an event -> publish the event -> some handler receives it and process it -> happy day.

Now, the sample uses MessageBus.Current, as it mentions, it depends on the DI setting (scoped/singleton etc.). 

The question is: if it's scoped (as the sample sets), will all the messages (from different sessions) be delivered and consumed?

And for the event consumer, I have a scenario that it uses in-memory transport, and each instance of the consumer only processes certain messages (same type). 

Maybe I should use "topic" for this?

**Comment by zarusz** [comment]
* The published messages are always routed onto a topic. The consumers are always consuming from a topic.
* Even when there are "no real" topics in `InMemory`, topics are the basis of routing.
* While publishing a message when topic is null or skipped (`IMessageBus.Publish(msg, topic)`) the default will be taken as per `DefaultTopic` configuration.
* In the `DomainEvents.WebApi` sample we use the type name as a topic:
(e.g. for C# message `OrderSubmittedEvent` the string "OrderSubmittedEvent" will be used). There is some reflection magic so that on app start I auto discover messages and consumers and register them into SMB. That way there is no need to repeat yourself with every new message / consumer a devloper adds. See [here](https://github.com/zarusz/SlimMessageBus/blob/master/src/Samples/Sample.DomainEvents.WebApi/Startup.cs#L101) and [here](https://github.com/zarusz/SlimMessageBus/blob/master/src/Samples/Sample.DomainEvents.WebApi/Startup.cs#L87). That is up to the developer how he wants to set this up - not part of SMB. I am just showing possibilities you could leverage .NET reflection easily.
* The message type you publish needs to match what the consumer is expecting (polymorphic messages could be supported as long as you configured your serializer e.g. for Newtonsoft.Json its the `$type` discriminator added to every message).

Now, regarding lifecycle and scoping in the context of InMemory SMB, and based on the `DomainEvents.WebApi`:
* The sample has IMessageBus as scope (so per request), but it may as well be configured as singleton as it does not store state. The sample has it per request to isolate instances for each pending web request:
`services.AddScoped<IMessageBus>(BuildMessageBus);`
* When you publish an event to the bus (in a web request), a handler matching topic+configuration 
 will be obtained from DI to handle that event. DI lookup is done on every message delivery (for `InMemory` at least).
* How it will be obtained it depends on what DI you've configured.
* The only handler present in the sample (`OrderSubmittedHandler`) has been registered as scoped in the DI:
`services.AddScoped<OrderSubmittedHandler>();`
* This means that events published to IMessageBus in web-request-1 scope will be consumed exactly by the `OrderSubmittedHandler` instance of web-request-1 scope (most likely lazy created as per MS DI implementation). That would be the most common use case - you want your domain logic to follow a request (unit of work) and be isolated from others requests (units of work).
* Now, If you wish one consumer/handler instance to recieve messages from across all the pending web requests that would be possible and you'd have to register the `OrderSubmittedHandler` as singleton. Likewise, if you wish a brand new instance of `OrderSubmittedHandler` with every event publish then register it as transient.

Now, the `MessageBus.Current`:
* Is just a way to look up the current `IMessageBus` from within your domain layer where there is no DI, etc. I am referring to an [onion](https://jeffreypalermo.com/2008/07/the-onion-architecture-part-1/) or hexagonal architecture here.
* This acts as a ServiceLocator pattern, and despite some calling it the anti-pattern it proves working really great in few of my commercial projects.
* In the `DomainEvents.WebApi` sample it configures the static Func to reach out to the ASP.NET Core `IHttpContextAccessor` to lookup the current pending request and ultimately return you the `IMessageBus` tied to the proper scope (per request / scoped or singleton depending how you registered the IMessageBus on your DI). See [here](https://github.com/zarusz/SlimMessageBus/blob/master/src/Samples/Sample.DomainEvents.WebApi/Startup.cs#L75).

As a side note:
The InMemory provider distributes messages within the same process (app domain) that they were created in. For any inter process comm you'd need to use Azure SB or other messaging system with SMB. I am planning on doing a hybrid SMB provider on which you'd be able to route messages between providers (some msg would be in memory, other would go to kafka).

It's really late here. I hope the above makes sense.

**Comment by unruledboy** [comment]
@zarusz  thanks a lot for the detailed explanation. It should be part of the wiki page to give the first time user a better understanding of the library.

**Comment by zarusz** [comment]
Yep, I plan to integrate this into the docs soon. Thank for the feedback. I appreciate it.

**Comment by zarusz** [comment]
Since the time this question has been raised the docs have been expanded and improved. I am closing this issue. Feel free to reopen if still, something isn't clear.
