### ISSUE TITLE
Kafka Headers

### ISSUE THREAD

**Issue by correa-juan** [zarusz/SlimMessageBus#155]
Hi ! 

We are sending an event with some headers but the headers are being sent  with extra quotes. 

![image](https://user-images.githubusercontent.com/127070539/223988964-f12a9bb9-5b74-453c-ba31-f7dd172fd6b9.png)

Do you know how to change that behavior ? 

thanks a lot ! 

Awesome project !

**Comment by zarusz** [comment]
Hello, what version of SMB Kafka are you using? What version of serializer plugin? Do you setup custom kafka header serializer in SMB?

**Comment by correa-juan** [comment]
Hello @zarusz  ! We are using: 

<img width="678" alt="image" src="https://user-images.githubusercontent.com/127070539/224062960-d9a67c56-832c-46be-b5ca-5be453094682.png">

this is our config: 

<img width="480" alt="image" src="https://user-images.githubusercontent.com/127070539/224063290-584394e3-d047-4e53-89fc-6fb3858f994f.png">

**Comment by zarusz** [comment]
The underlyint client (Confluent.Kafka library) required the header values to come as `byte[]`.

So since you're using the JsonMessageSerializer here, values are serialized to JSON. In the example the primitive value is string, so it would be serialized to `"string here"` which is what is expected. It does look weird in the tool that you've using to view the headers in Kafka (what tool are you usung?).

Now, if you need to send a string representation in such case, then the following custom serializer should do the trick:

```cs
public class StringMessageSerializer : IMessageSerializer
{
    private readonly Encoding _encoding;

    public StringMessageSerializer(Encoding encoding = null)
    {
        _encoding = encoding ?? Encoding.UTF8;
    }

    #region Implementation of IMessageSerializer

    public byte[] Serialize(Type t, object message)
    {
        if (message == null) return null;
        var payload = _encoding.GetBytes(message.ToString());
        return payload;
    }

    public object Deserialize(Type t, byte[] payload)
    {
        if (payload == null) return null;
        var str = _encoding.GetString(payload);
        // ToDo: maybe int.TryParse if you need to detect the primitive type
        // ToDo: maybe Guid.TryParse
        // ToDo: maybe bool.TryParse 
        return str;
    }

    #endregion
}

mbb.    
   .WithProviderKafka(new KafkaMessageBusSettings(kafkaBrokers)
   {
      HeaderSerializer = new StringMessageSerializer()
   });
```

Let me know if this works for you.

Also, why do you create the `MessageBusBuilder.Create()` instead of using the MS Dependency Injection integration using `.AddSlimMessageBus()`? Using the DI integration will setup various aspects of SMB.

**Comment by correa-juan** [comment]
it works ! 

thanks a lot !

**Comment by zarusz** [comment]
I might add this as the default header serializer in Kafka in the upcoming releases. 

Also, could you see my questions from previous reply? I am curious about your setup.
