### ISSUE TITLE
[Host.Redis] Delay in message arrival

### ISSUE THREAD

**Issue by GMillerVarian** [zarusz/SlimMessageBus#82]
Hi, we are using SlimMessageBus 1.4.0 with SlimMessageBus.Host.Redis 1.14.0 with Azure Cache for Redis. For the most part it is working well, however we have seen some rare cases where there is a delay after producing the message until the message arrives.

For example, in the following screenshot from Application Insights, the OnMessageProduced and OnMessageArrived events are being logged:

![image](https://user-images.githubusercontent.com/16961923/159051622-91ad26ab-8b2b-4b71-a2ea-1a4ba8a83666.png)

We have 2 pods running for our service, one pod receives the message immediately, but the other pod doesn't receive the message until 30 hours later. There is another case in the logs where they delay was 1h 45 mins for the second pod to receive the message. 

Is there a way to troubleshoot this further? Or is it a known issue? Would updating to latest packages resolve this?

Thanks!

**Comment by zarusz** [comment]
Hi @GMillerVarian , I definitely recommend upgrading to the latest version as there are bug fixes and improvements. That said, I am not aware of such an issue that would have been reported before or fixed.

Let me do some digging around, but if I cannot reproduce this I will need more details from you.

Setup:
So, as I understand your service has 2 pods in Kubernetes (2 running service instances), 

Problem:
One service publishes, the message arrived on 1st pod immediately, but hours later on the 2nd pod.

Question:
1.  Is the publishing happening in the same service as the consumption?
2. You're consuming from a topic (pub/sub) and not from a queue (list object in redis)? 
3. Are you using [Geo-Replication](https://azure.microsoft.com/en-us/blog/azure-redis-cache-geo-replication-is-now-generally-available/) for your Azure Redis instance? I assume both pods have the same redis connection string?

**Comment by GMillerVarian** [comment]
Thank you. To answer your questions:

1. Yes, the same service is both publishing & consuming the messages. We are using this as a mechanism to synchronize all pods for the same service based on an event in the service. 
2. Yes, we are specifying a topic in the producer / consumer configuration.
3. We are not using geo-replication. In this case we were using using the Basic tier for Redis.

**Comment by zarusz** [comment]
@GMillerVarian, I did some research and reviewed the SMB code. There is nothing obvious that comes to mind, that could have caused any delays. In general, I would not be surprised by messages being lost but them arriving with such a delay makes little sense. If one of your pods would be restarted then the message would be lost (added some [call out](https://github.com/zarusz/SlimMessageBus/blob/master/docs/provider_redis.md#consumer) about Redis delivery guarantees) and not delayed.

I am not using Azure Redis but rather the [Redis Labs](https://redislabs.com/) free cloud instance, so perhaps that is somehow related to the particular server implementation and even to the Basic tier being used.

However, in the latest preview version (since 1.17.1-rc2) I have added some additional logging when the Redis reconnects or some client-level protocol error occurs. Some of these are on debug level, so you'd have to increase the logging level (see the linked PR). Perhaps that will help to pinpoint the problem. These could use some debug level:

```
SlimMessageBus.Host.Redis.RedisTopicConsumer
SlimMessageBus.Host.Redis.RedisMessageBus
```

Additionally, I have upgraded to the latest StackExchange.Redis client. There have been some improvements made, but I don't expect any breakthrough in your case to be honest.

Please give the latest preview version a try (stable release will be here soon). Let me know if anything is observed or in case you are able to reproduce this.

**Comment by GMillerVarian** [comment]
Thank you for looking into this. We will update packages and keep an eye on it. Unfortunately it seems to be a very rare problem so it's a bit difficult to track.

**Comment by zarusz** [comment]
When I get some additional time, will try to run some additional tests against perhaps Azure Redis Basic.

**Comment by zarusz** [comment]
@GMillerVarian do you have any more observations or insights to share on this?

**Comment by GMillerVarian** [comment]
No, I think this issue can be closed. We currently have no direct proof that this issue was caused by SMB. We can re-open in the future if we see this again with the enhanced logging and package updates we have done. Thank you for your assistance!
